language: python
python:
- '3.6'
install:
- pip install -U tox-travis
- pip install -e .[dev]
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: OpenXbox
  password:
    secure: w6Iy194+NpTYg/GwUsgkDQTv6LlYtBfBcecT/AXv7SMF4aAMGvLFeNPPvsfW7Y7tT0xvGXwudAxHHUy2J7Kf6iPkLyS+B7sEIsBY2Ht1yIhqYnsBvPc+J0I30gCEJcIcAI1yI+mrA7YqD61bUsM6Z0TmhPqeMagDeJrY4SJtYBrHxvFbtoeA4Xs+OBtLYDIytu+0muwhvBNCAPVPPWian+R+sejSL+ymAwPsbO4cxvMzak/znOusRMzqCD4WohZkkWdiBu8GmT7XK+jYlV3/3MDWkMfS/1jjWxr0xQjLJ55m9D58tQXkEdvzoeHYB1/NRKoW97/3GHlWDNvS7IMiYVsf7zGYoP6bocSPlY9DpwHIGcB/wxHvRncZ4FQB7/b+qFvlSop7d+kWbZVDnlAI3HrR25erhUWrLuxTEelwGKak0w38eov6wrwnlmok0fVsIyorBVmIipp6V8ytFUNltj4ekufPNUYxTGtTvzOl95xUfqpry068qIJAf4qafBFSTrWZB+Vpgm3CUCpY9+dPdaZ6/X+yW1DkAz0vlDMtNwcWTMos20+GYa3BO9ZPnkxGB/eQQECCxQWwSCqG7y66Xb2JzHamcdbHhVIDGgXeNP0bdJ05Jl2PWqC/Rcn8LJNMQxNUCGwWEd5lt9KKt3hm+juc9Avhe9AZDezweMlcVSk=
  on:
    tags: true
    branch: master
    python: 3.6
